version: '3.9'

services:
  usagi:
    # ghcr.io image registry
    image: ghcr.io/sirubot/usagi:latest
    environment:
      - DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    ports:
      # Next.JS 3000 port
      - target: 3000 # next.js http port
        published: 3000
    networks:
      # Traefik reverse proxy
      - traefik-reverse-proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        # Enable traefik
        - traefik.enable=true
        # https entrypoint
        - traefik.http.routers.usagi.entrypoints=websecure
        # dash.cocochino.cafe will route -> :3000
        - traefik.http.routers.usagi.rule=Host(`dash.cocochino.cafe`)
        # traefik loadbalancer port
        - traefik.http.services.usagi.loadbalancer.server.port=3000

networks:
  traefik-reverse-proxy:
    external: true
