version: '3.8'

services:
  whoami:
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    image: traefik/whoami:latest
    deploy:
      labels:
        # traefik.enable=true and constraint label are needed because
        # of the restrictions we enforced in our traefik configuration
        - traefik.enable=true
        - traefik.http.routers.whoami.entrypoints=websecure
        - traefik.http.routers.whoami.rule=Host(`whoami.cocochino.cafe`)
        - traefik.http.routers.whoami.tls=true
        - traefik.http.routers.whoami.tls.certresolver=letsencrypt
        - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - traefik-reverse-proxy

networks:
  traefik-reverse-proxy:
    external: true
