version: '3'

services:
  portainer-ce:
    # Traefik reverse proxy will handle https traffic and redirect to portainer web ui
    labels:
      # Portainer Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.cocochino.cafe`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
    
    # Official portainer-ce image
    image: portainer/portainer-ce:latest
    ports:
      # TCP tunnel port that portainer will communicate with edge agents
      - "8000:8000"
      # Portainer web ui port (https)
      - "9443:9443"
    volumes:
      # Portainer will communicate with docker daemon of host machine
      - /var/run/docker.sock:/var/run/docker.sock
      # Portainer data volume
      - portainer_data:/data
    restart: always
volumes:
  portainer_data: