version: '3.2'

services:
  # Portainer agent
  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      # Docker socket binding
      - /var/run/docker.sock:/var/run/docker.sock
      # Docker volumes binding
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      # Portainer agent network
      - portainer-agent-network
    deploy:
      mode: global
      labels:
        - traefik.enable=false
      placement:
        constraints:
          - node.platform.os == linux
networks:
  portainer-agent-network:
    external: true
