version: '3'

services:
  portainer-ce:
    # Traefik reverse proxy will handle https traffic and redirect to portainer web ui
    labels:
      # Portainer frontend will be available at https://portainer.cocochino.cafe
      traefik.enable: true
      # Router portainer (https)
      traefik.http.routers.portainer-https.entrypoints: websecure
      traefik.http.routers.portainer-https.rule: Host(`portainer.cocochino.cafe`)
      traefik.http.routers.portainer-https.service: portainer-ce
      traefik.http.routers.portainer-https.tls: true
      traefik.http.routers.portainer-https.tls.certresolver: letsencrypt
      traefik.http.services.portainer-https.loadbalancer.server.port: 9000
    # Official portainer-ce image
    image: portainer/portainer-ce:latest
    ports:
      # TCP tunnel port that portainer will communicate with edge agents
      - "8000:8000"
      - "9000:9000"
    volumes:
      # Portainer will communicate with docker daemon of host machine
      - /var/run/docker.sock:/var/run/docker.sock
      # Portainer data volume
      - portainer_data:/data
    restart: always
    networks:
      - default

volumes:
  portainer_data:

networks:
  default:
    name: traefik-reverse-proxy