version: '3'

services:
  portainer-ce:
    # Traefik reverse proxy will handle https traffic and redirect to portainer web ui
    labels:
      # Portainer frontend will be available at https://portainer.cocochino.cafe
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`portainer.cocochino.cafe`)
      traefik.http.routers.portainer.entrypoint: websecure
      traefik.http.routers.portainer.tls.certresolver: letsencrypt
      traefik.http.routers.portainer.service: portainer-ce
      traefik.http.routers.portainer.port: 9443
    
    # Official portainer-ce image
    image: portainer/portainer-ce:latest
    ports:
      # TCP tunnel port that portainer will communicate with edge agents
      - "8000:8000"
      # Portainer web ui port (https)
      - "9443:9443"
    volumes:
      # Portainer will communicate with docker daemon of host machine
      - /var/run/docker.sock:/var/run/docker.sock
      # Portainer data volume
      - portainer_data:/data
    restart: always
volumes:
  portainer_data: