version: '3'

services:
  traefik-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Traefik health check
    healthcheck:
      test: wget --quiet --tries=1 --spider https://traefik.cocochino.cafe/api/rawdata || exit 1
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
    # .env file for traefik
    env_file:
      - .env
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=DEBUG"
      # Traefik address, secure address
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Lets encrypt cert resolver
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_CERT_RESOLVER_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      # The HTTP port
      - target: 80
        published: 80
        mode: host
      # The HTTPS port
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    # Labels for traefik
    labels:
      # Enable Traefik
      traefik.enable: true
      traefik.docker.network: traefik-reverse-proxy

      # Basic auth for traefik dashboard
      traefik.http.middlewares.traefik-dashboard-auth.basicauth.users: ${TRAEFIK_AUTH_USER}:${TRAEFIK_AUTH_PASS}

      # Middleware redirect-to-https
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      traefik.http.middlewares.redirect-to-https.redirectscheme.permanent: true

      # Router traefik dashboard (http)
      traefik.http.routers.dashboard.rule: Host(`traefik.cocochino.cafe`)
      traefik.http.routers.dashboard.entrypoints: web
      traefik.http.routers.dashboard.middlewares: redirect-to-https

      # Router traefik dashboard (https)
      traefik.http.routers.dashboard-https.rule: Host(`traefik.cocochino.cafe`)
      traefik.http.routers.dashboard-https.entrypoints: websecure
      traefik.http.routers.dashboard-https.middlewares: traefik-dashboard-auth
      traefik.http.routers.dashboard-https.tls: true
      traefik.http.routers.dashboard-https.tls.certresolver: letsencrypt
      traefik.http.routers.dashboard-https.service: api@internal
      traefik.http.services.dashboard-https.loadbalancer.server.port: 8080

    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Lets encrypt
      - ./letsencrypt:/letsencrypt
    restart: always

# Reverse proxy network
networks:
  default:
    external: true
    name: traefik-reverse-proxy
