version: "3.9"

services:
  redis:
    image: redis:alpine
    env_file:
      - .env
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - published: 6379
        target: 6379
        mode: host
